import 'semantic-ui-css/semantic.min.js'
import 'semantic-ui-css/semantic.min.css'
import 'semantic-ui-calendar/dist/calendar.min.js'
import 'semantic-ui-calendar/dist/calendar.min.css'
import 'semantic-ui-sidebar/sidebar.min.js'
import 'semantic-ui-sidebar/sidebar.min.css'
